/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ford_mustang_1965.glb --transform --types
Author: Pooya_dh (https://sketchfab.com/Pooya_dh)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/ford-mustang-1965-5f4e3965f79540a9888b5d05acea5943
Title: Ford Mustang 1965
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_8: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_23: THREE.Mesh;
    Object_25: THREE.Mesh;
    Object_27: THREE.Mesh;
    Object_29: THREE.Mesh;
    Object_31: THREE.Mesh;
    Object_33: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_36: THREE.Mesh;
    Object_37: THREE.Mesh;
    Object_39: THREE.Mesh;
    Object_40: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_44: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_48: THREE.Mesh;
    Object_49: THREE.Mesh;
    Object_51: THREE.Mesh;
    Object_53: THREE.Mesh;
    Object_55: THREE.Mesh;
    Object_56: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_60: THREE.Mesh;
    Object_62: THREE.Mesh;
    Object_64: THREE.Mesh;
    Object_66: THREE.Mesh;
    Object_67: THREE.Mesh;
    Object_69: THREE.Mesh;
    Object_71: THREE.Mesh;
    Object_73: THREE.Mesh;
    Object_75: THREE.Mesh;
    Object_77: THREE.Mesh;
    Object_79: THREE.Mesh;
    Object_81: THREE.Mesh;
    Object_83: THREE.Mesh;
    Object_85: THREE.Mesh;
    Object_87: THREE.Mesh;
    Object_89: THREE.Mesh;
    Object_91: THREE.Mesh;
    Object_93: THREE.Mesh;
    Object_95: THREE.Mesh;
    Object_97: THREE.Mesh;
    Object_99: THREE.Mesh;
    Object_101: THREE.Mesh;
    Object_102: THREE.Mesh;
    Object_103: THREE.Mesh;
    Object_104: THREE.Mesh;
    Object_106: THREE.Mesh;
    Object_107: THREE.Mesh;
    Object_109: THREE.Mesh;
    Object_111: THREE.Mesh;
    Object_112: THREE.Mesh;
    Object_114: THREE.Mesh;
    Object_116: THREE.Mesh;
    Object_118: THREE.Mesh;
    Object_120: THREE.Mesh;
    Object_122: THREE.Mesh;
    Object_123: THREE.Mesh;
    Object_125: THREE.Mesh;
    Object_127: THREE.Mesh;
    Object_129: THREE.Mesh;
    Object_131: THREE.Mesh;
    Object_133: THREE.Mesh;
    Object_135: THREE.Mesh;
    Object_137: THREE.Mesh;
    Object_139: THREE.Mesh;
    Object_140: THREE.Mesh;
    Object_142: THREE.Mesh;
    Object_144: THREE.Mesh;
    Object_146: THREE.Mesh;
    Object_148: THREE.Mesh;
    Object_149: THREE.Mesh;
    Object_150: THREE.Mesh;
    Object_152: THREE.Mesh;
    Object_154: THREE.Mesh;
    Object_156: THREE.Mesh;
    Object_158: THREE.Mesh;
    Object_160: THREE.Mesh;
    Object_162: THREE.Mesh;
    Object_164: THREE.Mesh;
    Object_166: THREE.Mesh;
    Object_167: THREE.Mesh;
    Object_168: THREE.Mesh;
    Object_170: THREE.Mesh;
    Object_172: THREE.Mesh;
    Object_173: THREE.Mesh;
    Object_175: THREE.Mesh;
    Object_177: THREE.Mesh;
    Object_179: THREE.Mesh;
    Object_181: THREE.Mesh;
    Object_183: THREE.Mesh;
    Object_185: THREE.Mesh;
    Object_187: THREE.Mesh;
    Object_189: THREE.Mesh;
    Object_191: THREE.Mesh;
    Object_193: THREE.Mesh;
    Object_195: THREE.Mesh;
    Object_197: THREE.Mesh;
    Object_199: THREE.Mesh;
    Object_201: THREE.Mesh;
    Object_203: THREE.Mesh;
    Object_205: THREE.Mesh;
    Object_207: THREE.Mesh;
    Object_209: THREE.Mesh;
    Object_211: THREE.Mesh;
    Object_212: THREE.Mesh;
    Object_213: THREE.Mesh;
    Object_214: THREE.Mesh;
    Object_215: THREE.Mesh;
    Object_216: THREE.Mesh;
    Object_217: THREE.Mesh;
    Object_219: THREE.Mesh;
    Object_221: THREE.Mesh;
    Object_223: THREE.Mesh;
    Object_224: THREE.Mesh;
    Object_226: THREE.Mesh;
    Object_227: THREE.Mesh;
    Object_229: THREE.Mesh;
    Object_231: THREE.Mesh;
    Object_233: THREE.Mesh;
    Object_235: THREE.Mesh;
    Object_236: THREE.Mesh;
    Object_237: THREE.Mesh;
    Object_239: THREE.Mesh;
    Object_241: THREE.Mesh;
    Object_242: THREE.Mesh;
    Object_244: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
    Color_02: THREE.MeshStandardMaterial;
    Color_04: THREE.MeshStandardMaterial;
    ["Color_04.001"]: THREE.MeshStandardMaterial;
    Miror: THREE.MeshStandardMaterial;
    Black: THREE.MeshStandardMaterial;
    interior: THREE.MeshStandardMaterial;
    Glass: THREE.MeshPhysicalMaterial;
    black1: THREE.MeshStandardMaterial;
    Metal_Part: THREE.MeshStandardMaterial;
    ["Material.012"]: THREE.MeshStandardMaterial;
    tail_lig: THREE.MeshStandardMaterial;
    Back_main_Light: THREE.MeshStandardMaterial;
    grille1: THREE.MeshStandardMaterial;
    textured: THREE.MeshStandardMaterial;
    Front_light: THREE.MeshStandardMaterial;
    material_0: THREE.MeshStandardMaterial;
    Metal_back: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    detail01: THREE.MeshPhysicalMaterial;
    interior_brown: THREE.MeshStandardMaterial;
    textur01: THREE.MeshPhysicalMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    bbea21f7: THREE.MeshStandardMaterial;
    detail02: THREE.MeshStandardMaterial;
    head_lig: THREE.MeshStandardMaterial;
    Head_Light: THREE.MeshStandardMaterial;
    Color_00: THREE.MeshStandardMaterial;
    ["Material.009"]: THREE.MeshStandardMaterial;
    logo_farmoon: THREE.MeshStandardMaterial;
    ["1_analog"]: THREE.MeshStandardMaterial;
    Carpet: THREE.MeshStandardMaterial;
    material: THREE.MeshStandardMaterial;
    ["Material.018"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    ["2011_06"]: THREE.MeshStandardMaterial;
    bfgoodri: THREE.MeshStandardMaterial;
    Logo_Ford: THREE.MeshStandardMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/ford_mustang_1965-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials.Color_04}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials["Color_04.001"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_11.geometry} material={materials.Miror} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Black} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.Color_04}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials["Color_04.001"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_33.geometry}
          material={materials.tail_lig}
        />
        <mesh
          geometry={nodes.Object_34.geometry}
          material={materials.Back_main_Light}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials.tail_lig}
        />
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials.Back_main_Light}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_39.geometry}
          material={materials.tail_lig}
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials.Back_main_Light}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_48.geometry}
          material={materials.Metal_Part}
        />
        <mesh geometry={nodes.Object_49.geometry} material={materials.Miror} />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_55.geometry}
          material={materials.Color_04}
        />
        <mesh
          geometry={nodes.Object_56.geometry}
          material={materials["Color_04.001"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_66.geometry}
          material={materials.textured}
        />
        <mesh
          geometry={nodes.Object_67.geometry}
          material={materials.Front_light}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_101.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Object_102.geometry}
          material={materials.interior_brown}
        />
        <mesh
          geometry={nodes.Object_103.geometry}
          material={materials.Metal_Part}
        />
        <mesh
          geometry={nodes.Object_104.geometry}
          material={materials.Material}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_106.geometry}
          material={materials.textur01}
        />
        <mesh
          geometry={nodes.Object_107.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_111.geometry}
          material={materials.Color_04}
        />
        <mesh
          geometry={nodes.Object_112.geometry}
          material={materials["Color_04.001"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_122.geometry}
          material={materials.Color_04}
        />
        <mesh
          geometry={nodes.Object_123.geometry}
          material={materials["Color_04.001"]}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_139.geometry}
          material={materials.Metal_Part}
        />
        <mesh
          geometry={nodes.Object_140.geometry}
          material={materials.textur01}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_148.geometry}
          material={materials.head_lig}
        />
        <mesh
          geometry={nodes.Object_149.geometry}
          material={materials.Metal_back}
        />
        <mesh
          geometry={nodes.Object_150.geometry}
          material={materials.Head_Light}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_166.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Object_167.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Object_168.geometry}
          material={materials.logo_farmoon}
        />
      </group>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_172.geometry}
          material={materials.Color_00}
        />
        <mesh
          geometry={nodes.Object_173.geometry}
          material={materials.Metal_Part}
        />
      </group>
      <group position={[0.16, 0.09, -0.03]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_211.geometry}
          material={materials.Metal_Part}
        />
        <mesh geometry={nodes.Object_212.geometry} material={materials.Glass} />
        <mesh
          geometry={nodes.Object_213.geometry}
          material={materials["1_analog"]}
        />
        <mesh
          geometry={nodes.Object_214.geometry}
          material={materials["1_analog"]}
        />
        <mesh
          geometry={nodes.Object_215.geometry}
          material={materials["1_analog"]}
        />
        <mesh
          geometry={nodes.Object_216.geometry}
          material={materials["1_analog"]}
        />
        <mesh
          geometry={nodes.Object_217.geometry}
          material={materials["1_analog"]}
        />
      </group>
      <group position={[0, 0.01, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_223.geometry}
          material={materials["Material.018"]}
        />
        <mesh
          geometry={nodes.Object_224.geometry}
          material={materials["Material.008"]}
        />
      </group>
      <group position={[0, 0.01, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_226.geometry}
          material={materials["2011_06"]}
        />
        <mesh
          geometry={nodes.Object_227.geometry}
          material={materials.bfgoodri}
        />
      </group>
      <group
        position={[0.11, 0.15, 0.28]}
        rotation={[-1.03, 0, 0]}
        scale={[0.01, 0.03, 0.03]}
      >
        <mesh geometry={nodes.Object_241.geometry} material={materials.Black} />
        <mesh
          geometry={nodes.Object_242.geometry}
          material={materials.Metal_Part}
        />
      </group>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Material}
        position={[0, 0, -0.02]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Color_02}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_14.geometry}
        material={materials.interior}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_16.geometry}
        material={materials.Glass}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_18.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_23.geometry}
        material={materials.Black}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_25.geometry}
        material={materials.Color_04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_27.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_29.geometry}
        material={materials.Color_02}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_31.geometry}
        material={materials["Material.012"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_42.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_44.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_46.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_51.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_53.geometry}
        material={materials.Color_04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_58.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_60.geometry}
        material={materials.grille1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_62.geometry}
        material={materials.Color_02}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_64.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_69.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_71.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_73.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_75.geometry}
        material={materials.Metal_back}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_77.geometry}
        material={materials.Glass}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_79.geometry}
        material={materials.Color_04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_81.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_83.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_85.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_87.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_89.geometry}
        material={materials["Material.010"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_91.geometry}
        material={materials.detail01}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_93.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_95.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_97.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_99.geometry}
        material={materials.Material}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_109.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_114.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_116.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_118.geometry}
        material={materials.Color_04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_120.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_125.geometry}
        material={materials.bbea21f7}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_127.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_129.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_131.geometry}
        material={materials.Color_04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_133.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_135.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_137.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_142.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_144.geometry}
        material={materials.Color_04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_146.geometry}
        material={materials.detail02}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_152.geometry}
        material={materials.Glass}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_154.geometry}
        material={materials.Color_00}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_156.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_158.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_160.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_162.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_164.geometry}
        material={materials.detail01}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_170.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_175.geometry}
        material={materials.Black}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_177.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_179.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_181.geometry}
        material={materials.Metal_back}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_183.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_185.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_187.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_189.geometry}
        material={materials.Color_02}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_191.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_193.geometry}
        material={materials.Color_04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_195.geometry}
        material={materials.black1}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_197.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_199.geometry}
        material={materials.Color_00}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_201.geometry}
        material={materials.Color_02}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_203.geometry}
        material={materials.Color_04}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_205.geometry}
        material={materials.Black}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_207.geometry}
        material={materials.Black}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_209.geometry}
        material={materials.Metal_Part}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_219.geometry}
        material={materials.Carpet}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_221.geometry}
        material={materials.material}
        position={[0, 0.01, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Object_229.geometry}
        material={materials.Carpet}
        position={[0.16, 0.11, 0.08]}
        scale={[0.09, 0.09, 0.16]}
      />
      <mesh
        geometry={nodes.Object_231.geometry}
        material={materials.Carpet}
        position={[-0.16, 0.11, 0.08]}
        scale={[0.09, 0.09, 0.16]}
      />
      <mesh
        geometry={nodes.Object_233.geometry}
        material={materials.Logo_Ford}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.11}
      />
      <mesh geometry={nodes.Object_235.geometry} material={materials.Black} />
      <mesh geometry={nodes.Object_236.geometry} material={materials.Glass} />
      <mesh
        geometry={nodes.Object_237.geometry}
        material={materials.Metal_Part}
      />
      <mesh
        geometry={nodes.Object_239.geometry}
        material={materials.Metal_Part}
        position={[0, 0.21, 0.16]}
        scale={0}
      />
      <mesh
        geometry={nodes.Object_244.geometry}
        material={materials["Material.002"]}
        position={[0.47, 0, 0]}
        rotation={[0, 0, 1.6]}
        scale={0.13}
      />
    </group>
  );
}

useGLTF.preload("/ford_mustang_1965-transformed.glb");
