/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Bracelet.glb --transform --types -sASSERTIONS
*/

import * as THREE from 'three'
import React, { useRef, useMemo, useContext, createContext } from 'react'
import { useGLTF, Merged } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Circle002: THREE.Mesh
  }
  materials: {
    ['Scratched Gold']: THREE.MeshStandardMaterial
  }
}

const context = createContext()
export function Instances({ children, ...props }) {
  const { nodes } = useGLTF('/Bracelet-transformed.glb') as GLTFResult
  const instances = useMemo(
    () => ({
      Circle: nodes.Circle002,
    }),
    [nodes]
  )
  return (
    <Merged meshes={instances} {...props}>
      {(instances) => <context.Provider value={instances} children={children} />}
    </Merged>
  )
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const instances = useContext(context)
  return (
    <group {...props} dispose={null}>
      <instances.Circle position={[-0.27, 2.17, 0.1]} rotation={[2.48, 0, -1.91]} scale={0.08} />
    </group>
  )
}

useGLTF.preload('/Bracelet-transformed.glb')
