/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Bracelet-Gold.glb --transform --types
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Circle001: THREE.Mesh
    Circle001_1: THREE.Mesh
    Circle001_2: THREE.Mesh
  }
  materials: {
    ['Scratched Gold']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/Bracelet-Gold-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.01, 0.2, 0]} rotation={[1.61, 0, -1.91]} scale={0.08}>
        <mesh geometry={nodes.Circle001.geometry} material={materials['Scratched Gold']} />
        <mesh geometry={nodes.Circle001_1.geometry} material={materials['Scratched Gold']} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials['Scratched Gold']} />
      </group>
    </group>
  )
}

useGLTF.preload('/Bracelet-Gold-transformed.glb')
