/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Bracelet-with-diamond-3.glb --transform --types
*/

import * as THREE from "three";
import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useWindowSize } from "react-use";
import { useFrame } from "react-three-fiber";
import { isMobile } from "react-device-detect";

type GLTFResult = GLTF & {
  nodes: {
    Circle001: THREE.Mesh;
    Circle001_1: THREE.Mesh;
    Circle001_2: THREE.Mesh;
    Circle016: THREE.Mesh;
  };
  materials: {
    ["Scratched Gold"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
  };
};

export function SimplifiedModel(props: JSX.IntrinsicElements["group"]) {
  const [scale, setScale] = useState(0.15);
  const { width } = useWindowSize();
  const groupRef = useRef<THREE.Group>(null);
  useEffect(() => {
    if (width < 768) {
      setScale(0.09);
    } else {
      setScale(0.15);
    }
  }, [width]);

  useFrame(() => {
    if (groupRef.current) {
      groupRef.current.rotation.y += 0.005;
    }
  });
  useFrame(({ mouse }) => {
    const { y } = mouse;
    if (groupRef.current) {
      groupRef.current.rotation.x = y * Math.PI * -0.1;
    }
  });
  const { nodes, materials } = useGLTF(
    "/models/simplified/Bracelet-with-diamond-3-transformed.glb"
  ) as GLTFResult;
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <group position={[0, -0.2, 0]} rotation={[1.8, 0, 1.2]} scale={scale}>
        <mesh
          geometry={nodes.Circle001.geometry}
          material={materials["Scratched Gold"]}
        />
        <mesh
          geometry={nodes.Circle001_1.geometry}
          material={materials["Scratched Gold"]}
        />
        <mesh
          geometry={nodes.Circle001_2.geometry}
          material={materials["Scratched Gold"]}
        />
      </group>
      <mesh
        geometry={nodes.Circle016.geometry}
        material={materials.Material}
        position={[0, -0.2, 0]}
        rotation={[1.8, 0, 1.2]}
        scale={scale}
      />
    </group>
  );
}
if (isMobile) {
  useGLTF.preload("/models/simplified/Bracelet-with-diamond-3-transformed.glb");
}
